spring.application.name=App
# Server port
server.port=8080

# Upload folder (relative to where you run the jar)
upload.dir=uploads

# Max file upload size (50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html